<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<?php
$exportViewModel = $block->getData('export_vm');

$products = $exportViewModel->createExport();
?>

<?php
    foreach ($products as $product) {
        foreach ($product as $item) {
            echo $item['sku']
                . " " . number_format((float)$item['qty_ordered'], 2)
                . " " . $item['order_id'] . '</br>';
        }
    }
?>

